version: '3.9'
services:
  posts-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: node
    container_name: web-posts
    ports:
      - "3300:5000"
    command: node dist/index.js
    volumes:
      - .:/usr/src/app

  bd-mongo:
    image: mongo
    container_name: posts-mongo-db
    ports: 
      - "4300:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nagu
      - MONGO_INITDB_ROOT_PASSWORD=nagupass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: